### ISSUE TITLE
TODO Next

### ISSUE THREAD

**Issue by Spozder** [rachelvolpert/swampyboston#1]
Server:
 - Determine affine transformation for coord -> pixel
 - Save geotiff as [Zarr](https://zarr.readthedocs.io/en/stable/tutorial.html) file
 - Setup Zarr file lookup using calculated pixel

Frontend
 - Get leaflet js working
 - Get georeferenced maps to overlay on leaflet js map
 - Georeference and download maps ([first](https://geo.leventhalmap.org/maps/9531#Export_tab))
 - On address submit: Load map, scroll to map, add overlay, add marker for address
 - Add opacity slider

**Comment by rachelvolpert** [comment]
- [x] about page
- [x] link git repo
- [x] display result text
- [x] favicon
- [x] address post 1995 - blue?
